### PR TITLE
Receipt fixes and state trie clearing detail

### LINKED ISSUE #55: Transactions causes split with Parity
This:

```
> personal.unlockAccount(eth.coinbase)
Unlock account 0x451122a4f0b6c0876d4b28643b04f53435182f71
Passphrase: 
true
> {from:eth.coinbase, to:'0x8b282d2123e77b9bc4b83eb732175e0406f3354a', value: web3.toWei(100, "ether"), gas:21000});
"0xda80a9ecc8d151a09bf715df035d3b91733ff668c78775e478c22d29b92460da"
> 
```

Caused this:

```
2019-06-11 20:11:38  Imported #10981 0x52e6…5f5d (0 txs, 0.00 Mgas, 0 ms, 0.50 KiB)
2019-06-11 20:11:40  Imported #10982 0xbbd9…4fe9 (0 txs, 0.00 Mgas, 0 ms, 0.50 KiB)
2019-06-11 20:12:08     3/25 peers   371 KiB chain 4 MiB db 0 bytes queue 539 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-11 20:12:10  Stage 5 block verification failed for #10983 (0x39b2…14c4)
Error: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x3519d32b9b94bb3c471361ba8d2b34352cb67c47ad0691a387daa995dfc0f347, found: 0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2019-06-11 20:12:10  
Bad block detected: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x3519d32b9b94bb3c471361ba8d2b34352cb67c47ad0691a387daa995dfc0f347, found: 0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
RLP: f90272f901fba0bbd92f55c08cf2eb89f0a96e70205259538c8f4c6b649762e394b1cdaa9c4fe9a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347943df1fc3a01d8a15a6aa4c95bf12f7631619996f1a0d551430df607393d31ff064ac39a52f0ca79f0bc6e7f53275b85214cf0e9ab01a08d1a812bcce43beddffa59165f59487e04604625cc6dc776753459267638c057a03519d32b9b94bb3c471361ba8d2b34352cb67c47ad0691a387daa995dfc0f347b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008317ba32822ae78347e7c4825208845cffeedc80a0d0154ad7318ff84466056ed40353f0f136b3fcdefb81ceea7d4dbbc6622c535b885b9f661ffde1b8aaf871f86f808504a817c800825208948b282d2123e77b9bc4b83eb732175e0406f3354a89056bc75e2d6310000080820a95a0cebcb1a24546dac41c2c949cbde4b4981891d2a38e27702eb73c541d6812980da04205d0dd175a42a3062d055277ac5290c40e45ce8c2710b7b812abfc1efccd5ec0
Header: Header { parent_hash: 0xbbd92f55c08cf2eb89f0a96e70205259538c8f4c6b649762e394b1cdaa9c4fe9, timestamp: 1560276700, number: 10983, author: 0x3df1fc3a01d8a15a6aa4c95bf12f7631619996f1, transactions_root: 0x8d1a812bcce43beddffa59165f59487e04604625cc6dc776753459267638c057, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [], state_root: 0xd551430df607393d31ff064ac39a52f0ca79f0bc6e7f53275b85214cf0e9ab01, receipts_root: 0x3519d32b9b94bb3c471361ba8d2b34352cb67c47ad0691a387daa995dfc0f347, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 21000, gas_limit: 4712388, difficulty: 1554994, seal: [[160, 208, 21, 74, 215, 49, 143, 248, 68, 102, 5, 110, 212, 3, 83, 240, 241, 54, 179, 252, 222, 251, 129, 206, 234, 125, 77, 187, 198, 98, 44, 83, 91], [136, 91, 159, 102, 31, 253, 225, 184, 170]], hash: Some(0x39b26e69c709287ebec0007440cc5c1ad73b06a98f4777fe8dc73aaca3d114c4) }
Uncles: 
Transactions:[Tx 0] UnverifiedTransaction { unsigned: Transaction { nonce: 0, gas_price: 20000000000, gas: 21000, action: Call(0x8b282d2123e77b9bc4b83eb732175e0406f3354a), value: 100000000000000000000, data: [] }, v: 2709, r: 93509840040241650265440443168223529970091543351406337441313959923251951081485, s: 29862923765667133073992970208953758916573727840587042244033021498471560826206, hash: 0xda80a9ecc8d151a09bf715df035d3b91733ff668c78775e478c22d29b92460da }

2019-06-11 20:12:38     0/25 peers   371 KiB chain 4 MiB db 0 bytes queue 539 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-11 20:13:08     0/25 peers   371 KiB chain 4 MiB db 0 bytes queue 539 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-11 20:13:38     0/25 peers   371 KiB chain 4 MiB db 0 bytes queue 539 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-11 20:14:08     0/25 peers   371 KiB chain 4 MiB db 0 bytes queue 539 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
```

### PR DESCRIPTION
**Pull request by austinabell**
Changes how the receipts are encoded and decoded to follow proper protocol of replacing intermediate state root with status encoding. Also performs state trie clearing at some appropriate points in a simulated system that was previously missed (see: `state.IntermediateRoot(config.IsAtlantis(parent.Number())` like changes).

Since previous receipts would have had status encoded and saved into the database, I have made the decoding backwards compatible:

```go
// DecodeRLP implements rlp.Decoder, and loads both consensus and implementation
// fields of a receipt from an RLP stream.
func (r *ReceiptForStorage) DecodeRLP(s *rlp.Stream) error {
	raw, err := s.Raw()
	if err != nil {
		return err
	}

	// Try decoding the receipt without Status first
	if err := decodeStoredReceiptRLP(r, raw); err == nil {
		return nil
	}

	return decodeOldStoredReceiptRLP(r, raw)
}
```

where decodeOldStoredReceiptRLP does not assume the ambiguous nature of PostStateOrStatus field of the Receipts and sets both fields specifically.

Also cleaned up the struct declaration for encoding/ decoding because encoding and decoding an untyped interface relying on positional variables and the confusing logic structure was very bad.

Edit: Resolves #55

### CODE REVIEW

**Comment by soc1c** [comment]
Is this [EIP-658](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md)?

**Comment by austinabell** [comment]
> Is this [EIP-658](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md)?

yes, the change necessary to enable 658 is included in this PR:

```go
rlp.Encode(w, []interface{}{r.statusEncoding(), r.CumulativeGasUsed, r.Bloom, r.Logs})
```

and all surrounding logic

from:

```go
rlp.Encode(w, []interface{}{r.PostState, r.CumulativeGasUsed, r.Bloom, r.Logs})
```

**Comment by GregTheGreek** [comment]
~Failed contract creation should not have success = 1~

~Reproduce-able test below:~

EDIT: Test was incorrect, I added a to field which no longer made it a contract deployment. 
```
~> eth.sendTransaction({from:eth.coinbase, to:'0x8b282d2123e77b9bc4b83eb732175e0406f3354a', data: "60606040525b6000151560125760006000fd5b5b5b60338060216000396000f30060606040525bfe00a165627a7a723058203d54db7a632777e6c9add0977c74024489bc162189d3ae9588c83b3561a0d1c30029", gas:45000});

"0x0a3fed3cfbf56324977c4b2ec86d4201c6f3a7805909f1e3bff1b6b6de2ca3d6"

 > eth.getTransactionReceipt("0x0a3fed3cfbf56324977c4b2ec86d4201c6f3a7805909f1e3bff1b6b6de2ca3d6")

{
  blockHash: "0xd3db64f50db9e14935621202cef4189756f08c8cbb6a973adcf934967deddc27",
  blockNumber: 40357,
  contractAddress: null,
  cumulativeGasUsed: 26200,
  from: "0x6ac28d519781d6321da388358c79cf08de1dddce",
  gasUsed: 26200,
  logs: [],
  root: "",
  status: 1,
  to: "0x8b282d2123e77b9bc4b83eb732175e0406f3354a",
  transactionHash: "0x0a3fed3cfbf56324977c4b2ec86d4201c6f3a7805909f1e3bff1b6b6de2ca3d6",
  transactionIndex: 0
}
```
Bytecode is equivalent to this (use [this version of remix to verify](https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.10+commit.f0d539ae.js)):
```
pragma solidity 0.4.10;

contract Test {
    
    function Test() payable {
        require(false);
    }
}
```

File: core/state_processor.go [hunk 1]
```diff
@@ -119,8 +119,15 @@ func ApplyTransaction(config *ChainConfig, bc *BlockChain, gp *GasPool, statedb
 	}
 
 	// Update the state with pending changes
+	var root []byte
+	if config.IsAtlantis(header.Number) {
+		statedb.Finalise(true)
+	} else {
+		root = statedb.IntermediateRoot(config.IsAtlantis(header.Number)).Bytes()
```
Comment (GregTheGreek) [inline core/state_processor.go:126]: IFF `isAtlantis === true` this code block won't get hit, you can probably just default it to false:
```suggestion
		root = statedb.IntermediateRoot(false).Bytes()
```

**Comment by noot** [comment]
@GregTheGreek you have a `to` field in your transaction, contract deployments don't have `to`. you're sending a normal tx which should be successful

**Review by GregTheGreek — CHANGES_REQUESTED** [review]

**Comment by GregTheGreek** [comment]
@noot woops thanks for that catch, disregard previous comment this looks to be functioning correctly

```
> eth.sendTransaction({from:eth.coinbase, data: "60606040525b6000151560125760006000fd5b5b5b60338060216000396000f30060606040525bfe00a165627a7a723058203d54db7a632777e6c9add0977c74024489bc162189d3ae9588c83b3561a0d1c30029", gas:90000});

"0xf2645dd6cc063096a2e326cc65834af3567560bd5b1de824ca3e4b5f31977746"

> eth.getTransactionReceipt("0xf2645dd6cc063096a2e326cc65834af3567560bd5b1de824ca3e4b5f31977746")

{
  blockHash: "0x6de5d8ccac56a2b3e529cd3ebe29a6ff4c59262c337c57651bce043e4958d7af",
  blockNumber: 40379,
  contractAddress: "0x9d1d7c22db1b325dfeb7603bcad1f487ef093afe",
  cumulativeGasUsed: 58247,
  from: "0x6ac28d519781d6321da388358c79cf08de1dddce",
  gasUsed: 58247,
  logs: [],
  root: "",
  status: 0,
  to: null,
  transactionHash: "0xf2645dd6cc063096a2e326cc65834af3567560bd5b1de824ca3e4b5f31977746",
  transactionIndex: 0
}
```

File: core/state_processor.go (hunk 1 above)
Comment (austinabell) [reply core/state_processor.go:126]: Future proofing since putting false is logically false, as state trie clearing should only occur when `IsAtlantis` is true. Is the same logically to put false in this case, but if intermediate root is needed in the future, I think it's better to be explicit.

**Review by GregTheGreek — APPROVED** [review]

**Review by noot — APPROVED** [review]

**Review by soc1c — APPROVED** [review]
